authors:
  team:
    name: Team
    description: All members
    avatar: https://github.com/Autismobox-TF2/.github/blob/main/images/autismobox_logo_transparent.png?raw=true
  jojo:
    name: Jojo
    description: Co-owner
    avatar: https://pbs.twimg.com/profile_images/1732542185931726850/_j9WEjR6_400x400.jpg
  xerg:
    name: Xerg
    description: Co-owner
    avatar: https://i.ytimg.com/vi/dQw4w9WgXcQ/maxresdefault.jpg